# Generated by Django 4.2.3 on 2023-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirm_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_is_confirmed',
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='страна'),
        ),
    ]
