# Generated by Django 4.2.3 on 2023-08-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_congratulated',
            field=models.BooleanField(default=False, verbose_name='поздравление отправлено'),
        ),
    ]
