# Generated by Django 4.2.3 on 2023-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='дата'),
        ),
    ]
